/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeTab: typeof import('./src/components/HomeTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tu: typeof import('./src/components/Tu.vue')['default']
    TuPanel: typeof import('./src/components/TuPanel.vue')['default']
    UBadge: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UButtonGroup: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue')['default']
    UForm: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UInput: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UProgress: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UTable: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
