/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createTree(label: string): Promise<FileTree>

export declare function createTreeItem(newItem: TreeItem): Promise<TreeItem>

export declare function createTreeItemContent(): Promise<TreeItemContent>

export declare function deleteTree(id: string): Promise<void>

export declare function deleteTreeItems(ids?: Array<string> | undefined | null): Promise<void>

export declare function fetchTree(id: string): Promise<FileTree>

export declare function fetchTrees(): Promise<Array<FileTree>>

export interface FileTree {
  id: string
  label: string
  items: Array<TreeItem>
}

export declare function getTreeItemContent(id: string): Promise<TreeItemContent>

export declare function hello(name: string): string

export declare function initDb(dbName: string): string

export declare function renameTreeItem(id: string, label: string): Promise<string>

export declare function setItemContentId(id: string, contentId?: string | undefined | null): Promise<string | null>

export interface TreeItem {
  id: string
  treeId: string
  parentId?: string
  contentId?: string
  label: string
  type: string
  prefix?: string
}

export interface TreeItemContent {
  name: string
  id: string
  url: string
  method: string
  params: Array<[string, string]>
  headers: Array<[string, string]>
  body: string
  selected: Record<string, Record<string, boolean>>
}

export declare function updateTree(data: string): Promise<void>

export declare function updateTreeItemContent(data: string): Promise<void>
