/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createTree(label: string): Promise<FileTree>

export declare function createTreeItemContent(): Promise<TreeItemContent>

export declare function fetchTree(id: number): Promise<FileTree>

export declare function fetchTrees(): Promise<Array<FileTree>>

export interface FileTree {
  id: number
  label: string
  items: Array<TreeItem>
}

export declare function getTreeItemContent(id: number): Promise<TreeItemContent>

export declare function hello(name: string): string

export declare function initDb(dbName: string): string

export interface TreeItem {
  contentId?: number
  label: string
  prefix?: string
  children?: Array<TreeItem>
}

export interface TreeItemContent {
  name: string
  id: number
  url: string
  method: string
  params: Array<[string, string]>
  headers: Array<[string, string]>
  body: string
  selected: Record<string, boolean>
}

export declare function updateTree(data: string): Promise<void>

export declare function updateTreeItemContent(data: string): Promise<void>
